package com.painrate.modules.patients.ui

object SQL_table {
    const val patients = "CREATE TABLE PATIENTS(PATIENT_ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT DEFAULT '', PHONE TEXT DEFAULT '', NOTES TEXT DEFAULT '', LOCATION TEXT DEFAULT '', DOB TEXT DEFAULT '')"



}